### ISSUE TITLE
WKWebView

### ISSUE THREAD

**Issue by MoSonLee** [MoSonLee/TIL#67]
- 인앱 브라우저와 같은 interactive web content를 보여주는 object
![image](https://user-images.githubusercontent.com/77050826/185361626-658e057a-899a-4149-9e8a-aaf4ea4c894d.png)
![image](https://user-images.githubusercontent.com/77050826/185361638-672edb42-9bbe-4fdf-b970-ca82558dcd10.png)
   - 이런식으로 extension에서 UISearchBarDelegate를 선언해준 후
   - searchbutton이 눌렸을 때 webView를 열게 선언해준 후 search bar와 함께 사용할 수 있다.

**Comment by Youngminah** [comment]
이게끝..?

**Comment by MoSonLee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ추가할게요..
